language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"

env:
  - REQUIREMENTS=colorama
  - REQUIREMENTS=default

install:
  - pip install -r .travis-$REQUIREMENTS-requirements.txt
  - pip install --editable .

script: make test

notifications:
  email: false
  irc:
    channels:
      - "chat.freenode.net#pocoo"
    on_success: change
    on_failure: always
    use_notice: true
    skip_join: true
